### ISSUE TITLE
Bug: validateResponse fails on impression_data

### ISSUE THREAD

**Issue by 10111282** [Unleash/unleash-client-php#226] opened 2024-09-17 11:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Our Unleash setup is the following:
unleash-client-php: v2.5.283
unleash edge:  v19.2.0
unleash server: 6.0.6

Currently we use Unleash Edge v18.0.1, it works as expected. We are trying to upgrade Edge to v19.2.0 which causes unleash-client-php (v2.5.283) to always return **null** in `validateResponse()`. The reason is that Unleash Edge v19.2.0 returns the response with a bit different fields, in particular it returns `impressionData` instead of `impression_data` (Unleash Edge v18.0.1).

Unleash client is configure like this:
```
  UnleashBuilder::create()
      ->withAppName(config('services.unleash.app.name'))
      ->withAppUrl(config('services.unleash.edge.url'))
      ->withInstanceId(config('services.unleash.edge.srv'))
      ->withProxy(config('services.unleash.edge.key'))
      ->withCacheTimeToLive(30)
      ->withStaleTtl(300)
      ->build()
```
While debugging it I can see that the request is sent to` /api/frontend/features/<feature name>`

<img width="1324" alt="unleash-client-validation" src="https://github.com/user-attachments/assets/9eefb19e-7b04-413e-b383-5ef453bf9ba8">

### To reproduce

1. Invoke $unleash->isEnabled('some-feature-name');
2. Expected to be **true** if the feature is enabled, but result is always **false**.

### Version

v2.5.283

### Expected behavior

Within `validateResponse()` it must expect `impressionData` instead of `impression_data`, or both for backward compatibility.

**Comment by gastonfournier** [comment] 2024-09-23 09:21
Hi! This was a fix from Unleash Edge [19.0.0](https://github.com/Unleash/unleash-edge/releases/tag/unleash-edge-v19.0.0) and it's one of the reasons of the major version bump. The problem is that PHP has implemented it wrong and looked at the snake case version: https://github.com/Unleash/unleash-client-php/blob/7353c74e1efde40634379282711bdb224df9a857/src/DTO/DefaultProxyFeature.php#L45 

I believe a simple solution would be to expect either snake case or camel case and support both for some versions. We can release that as a patch of the current version so the upgrade should be simple

**Comment by pallimalilsuhail** [comment] 2024-10-01 13:18
Hello @gastonfournier. I see you fixed and merged [here](https://github.com/Unleash/unleash-client-php/pull/227) 1 hour back. when can we expect the release? Thanks a lot.

**Comment by gastonfournier** [comment] 2024-10-01 13:43
Hi @pallimalilsuhail the release is on its way, it's going to be 2.6.x

**Closed as completed** 2024-10-03 07:32 UTC
Labels: bug
